# This is a basic workflow to help you get started with Actions
name: Github Actions Build

# Controls when the workflow will run
on: [push, pull_request] # those ignore-pathes don't work correctly?!?
#  push:
#    branches:
#      - master
#    paths-ignore:
#      - '.gitignore'
#      - '**.md'
#      - 'examples/**'
#  pull_request:
#    paths-ignore:
#      - '.gitignore'    
#      - '**.md'
#      - 'examples/**'      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1

      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
       
      - name: Build with nimble -y 
        run: nimble build -y
      - name: Test with nimble -y        
        run: nimble test -y
